<?php

namespace Spatie\ModelStates\Tests\Dummy\AllowAllTransitionsStateWithNoRegisteredStates;

use Spatie\ModelStates\Tests\Dummy\AllowAllTransitionsStateWithExplicitlyRegisteredStates\AllowAllTransitionsStateWithExplicitlyRegisteredStates;

class StateAWithNoRegisteredStates extends AllowAllTransitionsStateWithExplicitlyRegisteredStates
{

}
